### ISSUE TITLE
USER STORY: Set up Django Project

### ISSUE THREAD

**Issue by Faysal-Ahmed-Aweys** [Faysal-Ahmed-Aweys/Comfort-Cuisine#14]
As a **developer**, I can **Set up Django** so that **I can develop the site**

Tasks:
- [ ] Install Django
- [ ] Start Django project
- [ ] List required packages in requirements.txt file. (use freeze)
- [ ] Create Django app and add it to installed apps
- [ ] Make sure to add your IDE to allowed hosts to test the app works
- [ ] Install and configure PostgreSQL in project settings
- [ ] Install and configure Cloudinary in project settings
- [ ] Make sure you have .gitignore file
